### ISSUE TITLE
configurations for various tuned model

### ISSUE THREAD

**Issue by jihwanp** [Visual-AI/FROSTER#1]
Hi, it seems that you've only provided the configuration of the version when using  OpenVCLIP as a tuned model.
I wonder if you have any plans to release the configurations for other tuned models, such as ST-Adapter, AIM, etc.
Thanks

**Comment by OliverHxh** [comment]
Hi, Thanks for your reminder. I will soon update the files, please keep tuned.

**Comment by jihwanp** [comment]
Thanks. I'll wait!
