### ISSUE TITLE
Failed to fetch video after 100 retries.

### ISSUE THREAD

**Issue by zyb0424** [Visual-AI/FROSTER#11]
Hello, I encountered this issue while training with my own dataset. Could you please explain why this is happening? Can you provide some possible solutions? Thank you for the work you have done.!!!!!!!!!!!!!!!
/data0/zyb/UserZyb/data_01/froze_clip/fight_data/train/no_fight/segments_041.mp4 1
Failed to fetch video after 100 retries.
!!!!!!!!!!!!!!!
/data0/zyb/UserZyb/data_01/froze_clip/fight_data/train/fight/new_21.mp4 0
Failed to fetch video after 100 retries.
!!!!!!!!!!!!!!!

**Comment by OliverHxh** [comment]
Since we have discussed this in the emails, I will close this issue.
