### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by byminji** [Visual-AI/FROSTER#3]
Hi, 

Thank you for sharing an interesting work!
Could you please share the license for the code of this work? It would be greatly helpful.

Thank you :)

**Comment by OliverHxh** [comment]
Hi byminji,

The license we use is [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.en), which has been uploaded to our repo.

Hope this will be helpful.

Thanks.

Best,
Xiaohu

**Comment by byminji** [comment]
Thank you so much :)
