### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Hamzah-Luqman** [Visual-AI/FROSTER#5]
Thanks for sharing your amazing work. Could you please upload pre-trained models?

**Comment by OliverHxh** [comment]
Thanks for reaching out. We will release weights ASAP.

**Comment by OliverHxh** [comment]
Hi, the pre-trained model is now provided at the Google Drive Link: https://drive.google.com/file/d/1PzlGbx1664oHDrqwdAKsfydBRoKkb_ea/view?usp=sharing
