### ISSUE TITLE
hmdb51 mp4 video

### ISSUE THREAD

**Issue by wjj-w** [Visual-AI/FROSTER#7]
Hello, when I tested on the base set of hmdb51, some videos could not be read normally. I found that you changed their suffix to mp4 in val.csv, but the original video suffix was avi, even after I changed the suffix back to avi, it still could not be read normally. What is the reason? Looking forward to your reply！

**Comment by OliverHxh** [comment]
You should try using the ffmpeg command (or other commands) to transform the video format instead of directly renaming them. Here is an example:

```
ffmpeg -i input.avi -codec copy output.mp4
```
