### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by Mahmoud-Ali-FCIS** [Visual-AI/FROSTER#9]
Thanks for your great work.
Could you please upload the pre-trained models?

**Comment by OliverHxh** [comment]
Thanks for reaching out. We will release weights ASAP.

**Comment by OliverHxh** [comment]
Hi, the pre-trained model is now provided at the Google Drive Link: https://drive.google.com/file/d/1PzlGbx1664oHDrqwdAKsfydBRoKkb_ea/view?usp=sharing
